name: io
services:
  cache:
    image: redis:8.2.1-alpine3.22
    volumes:
      - ./data/redis/:/data
    ports:
      - 6379:6379
  db:
    image: postgres:18-bookworm
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "io"
